version: 2.0

phases:
  install:
    runtime-versions:
      java: corretto11
    pre_build:
      commands:
        - echo Nothing to do in the pre_build phase...
    build:
      commands:
        - echo Build started on `date`
        - mvn install
      post_build:
        commands:
          - echo Build completed on `date`
          - mv target/demoWar-1.0-SNAPSHOT.war ROOT.war
artifacts:
  files:
    - ROOT.war